image: docker:latest
services:
  - docker:dind


stages:
  - build
  - test
  - deploy

before_script:
  - ENVIRONMENT=$CI_COMMIT_BRANCH
  - TAG=$CI_COMMIT_SHA
  - PROJECT_NAME=$CI_PROJECT_NAME
  - echo ENVIRONMENT TAG PROJECT_NAME 

build-docker-image:
  stage: build
  variables:
    IMAGE_NAME: eu.gcr.io/yotta-square-ml3/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHA
  script:
  - echo $IMAGE_NAME
  - echo "$GITLAB_IAM_PRIVATE_KEY" > key.json
  - docker build . -t $IMAGE_NAME
  - docker login -u _json_key -p "$(cat key.json)" $IMAGE_NAME
  - docker push $IMAGE_NAME

unit-test:
  image: python:3.8.5
  stage: test
  script: 
    - pip install -r requirements.txt
    - pip install -e .
    - pytest lead_scoring/test/unit
  only:
    - develop
    - staging

deploy-api:
  stage: deploy
  image: google/cloud-sdk:257.0.0
  script:
    - echo "$GITLAB_IAM_PRIVATE_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project yotta-square-ml3 
    - gcloud config set compute/zone europe-west1-b 
    - gcloud container clusters get-credentials chaos-cluster 
    - cat deployment/deployment_api_template.yml | sed "s/ENVIRONMENT/$CI_COMMIT_BRANCH/" | sed "s/PROJECT_NAME/$CI_PROJECT_NAME/" | sed "s/TAG/$CI_COMMIT_SHA/" | kubectl apply -f -
    - cat deployment/load_balancer.yml | sed "s/ENVIRONMENT/$CI_COMMIT_BRANCH/" | sed "s/PROJECT_NAME/$CI_PROJECT_NAME/" | kubectl apply -f -

  only:
    - develop
    - staging
    - master
    - alex-import-model-from-gcp


