apiVersion: v1
kind: Pod

metadata:
  name: client-pod-ENVIRONMENT
  labels:
    app: client-app
    component: web

spec:
  containers:
    - name: client
      image: eu.gcr.io/yotta-square-ml3/clientreact:ENVIRONMENT-TAG
      ports:
        - containerPort: 3000
